### ISSUE TITLE
Torch not compiled with cuda enabled...

### ISSUE THREAD

**Issue by bbecausereasonss** [genmoai/models#57]
Tried man different versions now... conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1  pytorch-cuda=11.8 -c pytorch -c nvidia

This installation is very frustrating. Win 11.

**Comment by piradata** [comment]
try this

![image](https://github.com/user-attachments/assets/b5417e2f-ccbf-42a7-aca9-35f97850b11e)

**Comment by piradata** [comment]
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

https://web.archive.org/web/20241010054802/https://pytorch.org/get-started/locally/

**Comment by pyautoml** [comment]
This one did not help. I'm having the same error:   
File "D:\repository\external\models\venv\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by aesethtics-git** [comment]
> Tried man different versions now... conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> This installation is very frustrating. Win 11.

To piggyback on piradata's reply, try this:

uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

(adding uv to the beginning.)

FYI you can also see which version of torch is installed by using:

uv pip list

**Comment by arcinin1** [comment]
I have the same problem on Win 11. 

in my venv, pip list says:
torch                                    2.5.1+cu124
torchaudio                               2.5.1+cu124
torchvision                              0.20.1+cu124

But it still says AssertionError: Torch not compiled with CUDA enabled

**Comment by aesethtics-git** [comment]
> I have the same problem on Win 11.
> 
> in my venv, pip list says: torch 2.5.1+cu124 torchaudio 2.5.1+cu124 torchvision 0.20.1+cu124
> 
> But it still says AssertionError: Torch not compiled with CUDA enabled

try "uv pip list"
(different from "pip list")

**Comment by arcinin1** [comment]
Hey, you were right, it works now.
I though that uv is just a pip replacement written in Rust.

**Comment by piradata** [comment]
> Hey, you were right, it works now.
> I though that uv is just a pip replacement written in Rust.

it is, but it also saves the libs in a different place than pip, so one does not see the libs the other installed from what i got
